from __future__ import annotations

from typing import Any

from .color import ColorTexture
from .sdf import SDFTexture
from .texture import MultiOutputResult

class SDFNamespace:
    def bezier(self, a: Any, b: Any, c: Any) -> SDFTexture: ...
    def circle(self, center: Any, radius: Any) -> SDFTexture: ...
    def disc(self, center: Any, radius: Any) -> SDFTexture: ...
    def grid(self, offset: Any, size: Any, angle: Any = 0.0) -> SDFTexture: ...
    def half_plane(self, point: Any, normal: Any) -> SDFTexture: ...
    def line(self, a: Any, b: Any) -> SDFTexture: ...
    def rect(self, center: Any, size: Any, corner_radius: Any = 0.0, angle: Any = 0.0) -> SDFTexture: ...
    def rounded_rect(self, center: Any, size: Any, corner_radius: Any, angle: Any = 0.0) -> SDFTexture: ...
    def text(self, value: Any, size: Any = 64, ox: Any = 0, oy: Any = 0, path: Any = 'fonts/georgia_regular.ttf', samples: Any = 16, cache_size: Any = 128, line_height: Any = 1.2, oversample: Any = 2.0, min_render_size: Any = 64) -> SDFTexture: ...
    def triangle(self, point_1: Any, point_2: Any, point_3: Any) -> SDFTexture: ...

class ColorNamespace:
    def clear(self, color: Any) -> ColorTexture: ...
    def clear_color(self, color: Any) -> ColorTexture: ...
    def film_grain(self) -> ColorTexture: ...
    def linear_gradient(self, a: Any, b: Any, color1: Any, color2: Any) -> ColorTexture: ...
    def noise(self) -> ColorTexture: ...
    def perlin_noise(self) -> ColorTexture: ...
    def radial_gradient(self, a: Any, color1: Any, color2: Any, inner: Any = 0, outer: Any = 100) -> ColorTexture: ...
