from __future__ import annotations

from typing import Any

from .texture import PostNamespace, TextureNode

class ColorSpaceMode:
    LAB: str
    RGB: str

class ColorTexture(TextureNode):
    kind: str
    mode: str
    @property
    def post(self) -> PostNamespace: ...
    def over(self, other: Any) -> ColorTexture: ...
    def to_lab(self) -> ColorTexture: ...
    def to_rgb(self) -> ColorTexture: ...
    def alpha_overlay(self, other: Any) -> ColorTexture: ...
    def blur(self, n: Any = 0, base: Any = 9) -> ColorTexture: ...
    def blur_13(self, n: Any = 0) -> ColorTexture: ...
    def blur_9(self, n: Any = 0) -> ColorTexture: ...
    def dither_1bit(self) -> ColorTexture: ...
    def dithering(self) -> ColorTexture: ...
    def invert(self) -> ColorTexture: ...
    def layer_mask(self, top: Any, mask: Any) -> ColorTexture: ...
    def mask(self, top: Any, mask: Any) -> ColorTexture: ...
    def multiply(self, other: Any) -> ColorTexture: ...
    def transparency(self, alpha: Any) -> ColorTexture: ...
