from __future__ import annotations

from typing import Any

from .color import ColorTexture
from .texture import MultiOutputResult, TextureNode

class SDFTexture(TextureNode):
    kind: str
    def __or__(self, other: Any) -> SDFTexture: ...
    def __and__(self, other: Any) -> SDFTexture: ...
    def __sub__(self, other: Any) -> SDFTexture: ...
    def intersect(self, other: Any) -> SDFTexture: ...
    def mask(self, inflate: Any = 0.0, color0: Any = (0.0, 0.0, 0.0, 1.0), color1: Any = (1.0, 1.0, 1.0, 1.0)) -> ColorTexture: ...
    def abs(self) -> SDFTexture: ...
    def fill(self, fg_color: Any, bg_color: Any = (0.0, 0.0, 0.0, 1.0), inflate: Any = 0.0, inner: Any = -1.5, outer: Any = 0.0) -> ColorTexture: ...
    def fill_from_texture(self, layer: Any, background: Any = (0.0, 0.0, 0.0, 0.0), inflate: Any = 0) -> ColorTexture: ...
    def generate_mask(self, inflate: Any = 0.0, color0: Any = (0.0, 0.0, 0.0, 1.0), color1: Any = (1.0, 1.0, 1.0, 1.0)) -> ColorTexture: ...
    def interpolate(self, other: Any, t: Any = 0.5) -> SDFTexture: ...
    def intersection(self, other: Any) -> SDFTexture: ...
    def masked_union(self, other: Any) -> MultiOutputResult: ...
    def outline(self, fg_color: Any, bg_color: Any = (0.0, 0.0, 0.0, 0.0), inflate: Any = 0.0) -> ColorTexture: ...
    def partial_derivative(self) -> ColorTexture: ...
    def repeat(self, s: Any = 15.0) -> SDFTexture: ...
    def shadow(self, distance: Any = 10, inflate: Any = 0, transparency: Any = 0.75) -> ColorTexture: ...
    def smooth_union(self, other: Any, k: Any = 0.025) -> SDFTexture: ...
    def subtract(self, other: Any) -> SDFTexture: ...
    def union(self, other: Any) -> SDFTexture: ...
