from __future__ import annotations

from typing import Any

from .color import ColorTexture
from .texture import MultiOutputResult, TextureNode

class SDFTexture(TextureNode):
    kind: str
    def __or__(self, other: Any) -> SDFTexture: ...
    def __and__(self, other: Any) -> SDFTexture: ...
    def __sub__(self, other: Any) -> SDFTexture: ...
    def intersect(self, other: Any) -> SDFTexture: ...
    def mask(self, inflate: Any = 0.0, color0: Any = (0.0, 0.0, 0.0, 1.0), color1: Any = (1.0, 1.0, 1.0, 1.0)) -> ColorTexture: ...
    def abs(self) -> SDFTexture: ...
    def fill(self, fg_color: Any, bg_color: Any = (0.0, 0.0, 0.0, 1.0), inflate: Any = 0.0, inner: Any = -1.5, outer: Any = 0.0) -> ColorTexture: ...
    def fill_from_texture(self, layer: Any, background: Any = (0.0, 0.0, 0.0, 0.0), inflate: Any = 0) -> ColorTexture: ...
    def generate_mask(self, inflate: Any = 0.0, color0: Any = (0.0, 0.0, 0.0, 1.0), color1: Any = (1.0, 1.0, 1.0, 1.0)) -> ColorTexture: ...
    def half_plane(self, point: Any, normal: Any) -> SDFTexture: ...
    def interpolate(self, other: Any, t: Any = 0.5) -> SDFTexture: ...
    def intersection(self, other: Any) -> SDFTexture: ...
    def isolines(self, fg_color: Any, bg_color: Any = (0.0, 0.0, 0.0, 0.0), inflate: Any = 0.0, spacing: Any = 0.75, line_width: Any = 0.2, feather: Any = 0.15, phase: Any = 0.0) -> ColorTexture: ...
    def light(self, fg_color: Any, bg_color: Any = (0.0, 0.0, 0.0, 0.0), light_dir: Any = (-0.45, -0.65, 0.7), ambient: Any = 0.35, diffuse: Any = 0.75, specular: Any = 0.2, shininess: Any = 24.0, normal_strength: Any = 4.0, bevel: Any = 8.0, shade_background: Any = False, background_bevel: Any = 0.0, height_profile: Any = 0.0, height_gamma: Any = 1.0, height: Any = 1.0, inflate: Any = 0.0, inner: Any = -1.5, outer: Any = 1.5) -> ColorTexture: ...
    def masked_union(self, other: Any) -> MultiOutputResult: ...
    def outline(self, fg_color: Any, bg_color: Any = (0.0, 0.0, 0.0, 0.0), inflate: Any = 0.0) -> ColorTexture: ...
    def partial_derivative(self) -> ColorTexture: ...
    def repeat(self, s: Any = 15.0) -> SDFTexture: ...
    def shadow(self, distance: Any = 10, inflate: Any = 0, transparency: Any = 0.75) -> ColorTexture: ...
    def smooth_union(self, other: Any, k: Any = 0.025) -> SDFTexture: ...
    def subtract(self, other: Any) -> SDFTexture: ...
    def union(self, other: Any) -> SDFTexture: ...
