from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .color import ColorTexture

class TextureNode:
    def render(self, ctx: Any = None, params: Any = None, cache: Any = None) -> Any: ...
    def show(self, ctx: Any = None, params: Any = None, cache: Any = None, conversion: Any = True, size: Any = None) -> None: ...
    def save(self, name: Any = './image.png', ctx: Any = None, params: Any = None, cache: Any = None, conversion: Any = True, size: Any = None) -> None: ...
    def named(self, label: Any) -> Any: ...
    def cache(self, label: Any = None) -> Any: ...
    def uncached(self) -> Any: ...

class PostNamespace:
    def to_lab(self) -> ColorTexture: ...
    def to_rgb(self) -> ColorTexture: ...
    def blur(self, n: Any = 0, base: Any = 9) -> ColorTexture: ...
    def blur_13(self, n: Any = 0) -> ColorTexture: ...
    def blur_9(self, n: Any = 0) -> ColorTexture: ...
    def dither_1bit(self) -> ColorTexture: ...
    def dithering(self) -> ColorTexture: ...
    def invert(self) -> ColorTexture: ...

class MultiOutputResult:
    op: str
    inputs: tuple[Any, ...]
    params: tuple[Any, ...]
    label: Optional[str]
    should_cache: bool
    kind: str
    def render(self, ctx: Any, params: Optional[dict[str, Any]] = ..., cache: Any = ...) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
